let injectedFoodLabel = {
  gmWgt: "35",
  carbsCalsPct: 70,
  sogHexColor: -14510844,
  iconSrc: "https://assets.mynetdiary.com/bean/i507.png",
  foodId: "YZjig+Azh5jfglaRW5ii8pdApUhZvEGK",
  allOmega: [],
  imageSrc: "https://assets.mynetdiary.com/SystemPictures/web/18078.webp",
  rawCalories: 85,
  serving: "slice (35g)",
  gradeValue: "A",
  foodName: "Grof volkoren brood by Lidl",
  servings: [
    {
      gmWgt: "35 g",
      pct: 7,
      amount: "1",
      preciseCalories: 85.000000001,
      weightId: 1,
      calories: "85",
      title: "slice",
      recent: false,
    },
    {
      gmWgt: "28.3 g",
      pct: 6,
      amount: "1",
      preciseCalories: 68.84884289413797,
      weightId: 987,
      calories: "69",
      title: "oz",
      recent: false,
    },
    {
      gmWgt: "1 g",
      pct: 0,
      amount: "1",
      preciseCalories: 2.4285714286,
      weightId: 988,
      calories: "2",
      title: "gram",
      recent: false,
    },
    {
      gmWgt: "453.6 g",
      pct: 100,
      amount: "1",
      preciseCalories: 1101.5814863062076,
      weightId: 990,
      calories: "1,102",
      title: "lb",
      recent: false,
    },
  ],
  allVitamins: [],
  protein: {
    values: {
      rawValue: 4.5999999990000005,
      pctDv2000: 9,
      leftOrOverLabel: "Left 45g",
      valueAndUnit: "5g",
    },
    id: 203,
    title: "Protein",
    articleUrl: "/the-benefits-of-eating-protein.html",
  },
  allMct: [],
  satFat: {
    values: {
      rawValue: 0.1000000015,
      pctDv2000: 1,
      leftOrOverLabel: "Left 19.9g",
      valueAndUnit: "0.1g",
    },
    id: 606,
    title: "Saturated Fat",
    articleUrl: "/dietary-fats.html",
  },
  diabetesCarbCount: {
    values: {
      rawValue: 14.00001,
      leftOrOverLabel: "No target",
      valueAndUnit: "14g",
    },
    id: 1102,
    title: "Diabetes Carb Count",
    articleUrl: "/learn-about-diabetes.html#trackingCarbohydrates",
  },
  secondaryNutrients: [],
  showFoodGrade: true,
  burnTimes: {
    bycicling: { minutes: 11, minutesLabel: " min", hoursLabel: "" },
    swimming: { minutes: 15, minutesLabel: " min", hoursLabel: "" },
    walking: { minutes: 37, minutesLabel: " min", hoursLabel: "" },
    jogging: { minutes: 11, minutesLabel: " min", hoursLabel: "" },
  },
  totalCarbs: {
    values: {
      rawValue: 14,
      pctDv2000: 5,
      leftOrOverLabel: "Left 261g",
      valueAndUnit: "14g",
    },
    id: 205,
    title: "Total Carbs",
    articleUrl: "/3-types-of-carbohydrate.html",
  },
  allCarbsRelated: [],
  gradeLabel: "Food Grade",
  totalFat: {
    values: {
      rawValue: 0.5999999985,
      pctDv2000: 1,
      leftOrOverLabel: "Left 77.4g",
      valueAndUnit: "0.6g",
    },
    id: 204,
    title: "Total Fat",
    articleUrl: "/dietary-fats.html",
  },
  fiber: {
    values: {
      rawValue: 2.8,
      pctDv2000: 10,
      leftOrOverLabel: "Left 25g",
      valueAndUnit: "3g",
    },
    id: 291,
    title: "Dietary Fiber",
    articleUrl: "/great-food-sources-of-fiber.html",
  },
  allOther: [],
  caloriesPctDv2000: 4,
  sugars: {
    values: { rawValue: 0.7, leftOrOverLabel: "No target", valueAndUnit: "1g" },
    id: 269,
    title: "Total Sugars",
    articleUrl: "/3-types-of-carbohydrate.html",
  },
  clearServing: "slice",
  calories: "85cals",
  mainNutrientsCount: 9,
  vendorName: "Lidl",
  mobileImageSrc:
    "https://assets.mynetdiary.com/SystemPictures/web/mobile/18078.webp",
  netCarbs: {
    values: {
      rawValue: 11.2,
      leftOrOverLabel: "No target",
      valueAndUnit: "11g",
    },
    id: 1100,
    title: "Net Carbs",
    articleUrl: "/3-types-of-carbohydrate.html",
  },
  allMinerals: [],
  nccRelated: false,
  sodium: {
    values: {
      rawValue: 127.9999999985,
      pctDv2000: 6,
      leftOrOverLabel: "Left 2,172mg",
      valueAndUnit: "128mg",
    },
    id: 307,
    title: "Sodium",
    articleUrl: "/how-to-reduce-sodium-intake.html",
  },
  allProteins: [],
  rawGmWgt: 35,
  cleanFoodName: "Grof Volkoren Brood",
  totalFatCalsPct: 7,
  proteinCalsPct: 23,
  gradeLabelShort: "grade",
};
